version: "3.7"
services:
  app:
    build:
      args:
        user: nagai
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: time-manager
    container_name: time-manager-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - time-manager

  db:
    image: mysql
    container_name: time-manager-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: timeManager
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 8060:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - time-manager

  nginx:
    image: nginx
    container_name: time-manager-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - time-manager

  redis:
    image: redis
    container_name: time-manager-redis
    restart: unless-stopped
    ports:
      - 8030:6379
    networks:
      - time-manager

networks:
  time-manager:
    driver: bridge
