#!/bin/bash

root_uid=0      #Root has $UID 0
success=0
e_userexists=70
e_notroot=65        #Not root
type=$1
delete_user=delete_user

#Run as root, and this checks to see if the creater is in root. If not, will not run
if [ "$UID" -ne "$root_uid" ]; then
    echo "Sorry must be in root to run this script"
    exit $e_notroot
fi

if [ "$type" = "create" ]; then

	if [ $# -eq 3 ]; then
		username=$2
		pass=$3

		grep -q "$username" /etc/passwd

		if [ $? -eq $success ]; then
			echo "User $username already exists"
			echo "Please choose another username"
			exit $e_userexists 
		fi

		useradd $username -d /home/$username -m;
		echo "$username:$pass" | sudo chpasswd

		sudo usermod -G sftpusers $username
		sudo chown root:root /home/$username
		sudo chmod 755 /home/$username
		sudo mkdir /home/$username/public_html
		sudo chown $username:$username /home/$username/public_html

		echo "The account is setup"
	else
		echo "this program needs 3 arguments and you have given $#"
		echo "you have to call the script $0 username and the pass"
		exit 0
	fi
fi

if [ "$type" = "delete" ]; then
	sudo deluser --remove-home $2
	echo "Deleted user $2"
fi
