#!/bin/bash

user=$1
pass=$2



if [ "${user}" != "" ] && [ "${pass}" != "" ]; then
	echo "${user}:${pass}" | chpasswd
else
	echo "ERROR: Please provide valid data"
	echo "EXAMPLE: update_user_password username new_password"
fi
